image: node:6.11.3

pages:
  stage: deploy
  script:
  - npm i
  - npm run build
  - rm -r public
  - mkdir public
  - cp -r dist/* public
  artifacts:
    paths:
    - build
    - public
    - node_modules
  only:
    - master
    - development