image: registry.temando.io/continuous-integration/node

pages:
  stage: deploy
  script:
  - npm i
  - npm run build
  - mkdir .public
  - cp -r dist/* .public
  - mv .public public
  artifacts:
    paths:
    - public
    - node_modules
  only:
    - master