image: node:6.11.3

stages:
  - build
  - validate
  - deploy

install:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 week

code lint:
  stage: validate
  script:
    - npm run lint
  dependencies:
    - install

pages:
  stage: deploy
  script:
  - npm run build
  - mkdir .public
  - cp -r dist/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
    - master