# Site settings
title: Pure React using GitLab Pages
email: ngochuynh1991@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "tools" # the subpath of your site, e.g. /blog
url: "/huynhdn-react-boilerplate.gitlab.io" # the base hostname & protocol for your site
github_username:  ptit9x

# Build settings
markdown: kramdown
exclude: ["README.md"]